// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIzUyv-q_PcWRVr2zTtu0MHVAypfFHnFU',
    appId: '1:176584428229:web:501bf757690334a3c47eac',
    messagingSenderId: '176584428229',
    projectId: 'health-tracker-aa3ae',
    authDomain: 'health-tracker-aa3ae.firebaseapp.com',
    storageBucket: 'health-tracker-aa3ae.appspot.com',
    measurementId: 'G-JJRHGV7X2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7p83rTiC-jjnZXMJI8wkqC5X9vk5aok',
    appId: '1:176584428229:android:09f33e75c4b01d57c47eac',
    messagingSenderId: '176584428229',
    projectId: 'health-tracker-aa3ae',
    storageBucket: 'health-tracker-aa3ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCceC0xok3iahKwYquW2p66s9lLDodFkDI',
    appId: '1:176584428229:ios:5f3e95c7beb459c4c47eac',
    messagingSenderId: '176584428229',
    projectId: 'health-tracker-aa3ae',
    storageBucket: 'health-tracker-aa3ae.appspot.com',
    iosClientId: '176584428229-e8pdl44evv4sk4genkc1f2ajlg207v2o.apps.googleusercontent.com',
    iosBundleId: 'com.anis.healthtracker',
  );
}
